name: Deploy to automation

on:
  push:
    branches:
      - testing-automation

jobs:
  vapor:
    name: deploy-automation
    runs-on: ubuntu-latest
    steps:
      - name: push event
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
            https://api.github.com/repos/webinarinc/file-manager-backend/actions/workflows/automation.yml/dispatches \
            -d '{ "ref": "testing-automation" }'
