name: Deploy to production

on:
  push:
    branches:
      - develop

jobs:
  vapor:
    name: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: push event
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
            https://api.github.com/repos/webinarinc/file-manager-backend/actions/workflows/production.yml/dispatches \
            -d '{ "ref": "master" }'
